### ISSUE TITLE
dev_appserver:fix_sys_path manipulation causes an import failure

### ISSUE THREAD

**Issue by brunoripa** [kaste/pytest-beds#4]
Very weird thing happening, i had no chance to find any help so i try here.

I am creating an appengine standard app and am using `google.cloud.storage` package. The app works, and files are correctly sent to the server. The problem is that when i try to launch tests with `pytest` and `pytest-beds` the path manipulation made the latter (`dev_appserver:fix_sys_path`) puts the google cloud sdk before my custom dependencies.

This causes `import error`s for `google.auth.crypt.base` and `pyasn1_modules.pem` which exist in the github versions of the packages, but are shipped in google-cloud-sdk at older versions triggering the issue.

I am almost sure this is not a pytest-beds bug, but anyone able to help ?

Thanks

**Comment by kaste** [comment]
I had this. It was a nightmare. Basically, you provide `--no-gae`, so that this plugin does not call `fix_sys_path`. Then in your `virtualenv` in `site-packages` you create a file say `gae.pth` (only the extension matters) 

```
<insert path to gae>
import dev_appserver; dev_appserver.fix_sys_path()  # <- so that this works
import sys; sys.path.insert(0, <insert other paths that you want to be on top of that>)
```

Now you have a 'fixed' virtual environment, so that e.g. a local `ipython` can just import the google stuff. The same way a local `pytest` can just use google appengine.

These are the bits I remember.

**Comment by kaste** [comment]
Maybe you don't have to set `--no-gae` because `fix_sys_path()` is wise enough to not patch twice. Hard to say.  EDIT: What I remember, I don't set `--no-gae`, but I'm confident that I have something like the above `gae.pth` bc I actually see that file in my repo 😄 Wish you luck. 😉

**Comment by brunoripa** [comment]
Thanks, i'll have a look.
